#!/usr/bin/env bash
# Clone/update importable crypto libraries and generate env.sh.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MANIFEST="$ROOT/libs.tsv"
LINK_DIR="$ROOT/links"

DO_UPDATE=true
DO_SAGE_INSTALL=true
DRY_RUN=false

usage() {
  cat <<'EOF'
Usage: ./setup.sh [options]

Options:
  --no-update          Do not pull existing repositories.
  --no-sage-install    Do not install Sage packages such as cuso.
  --dry-run            Print actions without changing repositories.
  -h, --help           Show this help.

The source of truth is libs.tsv. Edit it to add, remove, or move libraries.
EOF
}

for arg in "$@"; do
  case "$arg" in
    --no-update) DO_UPDATE=false ;;
    --no-sage-install) DO_SAGE_INSTALL=false ;;
    --dry-run) DRY_RUN=true ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $arg" >&2; usage; exit 1 ;;
  esac
done

log() { printf '[crypto-libs] %s\n' "$*"; }
warn() { printf '[crypto-libs] warning: %s\n' "$*" >&2; }
die() { printf '[crypto-libs] error: %s\n' "$*" >&2; exit 1; }

run() {
  if $DRY_RUN; then
    printf '[dry-run]'
    printf ' %q' "$@"
    printf '\n'
  else
    "$@"
  fi
}

is_safe_relpath() {
  case "$1" in
    ""|/*|.*|*/../*|../*|*/..) return 1 ;;
    *) return 0 ;;
  esac
}

manifest_records() {
  awk -F'\t' '
    !/^[[:space:]]*(#|$)/ {
      printf "%s\034%s\034%s\034%s\034%s\034%s\n", $1, $2, $3, $4, $5, $6
    }
  ' "$MANIFEST"
}

clone_or_update() {
  local name="$1" relpath="$2" url="$3" branch="$4"
  local dir="$ROOT/$relpath"

  is_safe_relpath "$relpath" || die "unsafe path for $name: $relpath"
  mkdir -p "$(dirname "$dir")"

  if [ -d "$dir/.git" ]; then
    if $DO_UPDATE; then
      log "update $name"
      run git -C "$dir" pull --ff-only
    else
      log "skip update $name"
    fi
  elif [ -e "$dir" ] && [ -n "$(find "$dir" -mindepth 1 -maxdepth 1 -print -quit 2>/dev/null)" ]; then
    die "$dir exists but is not an empty git checkout"
  else
    log "clone $name"
    if [ "$branch" = "-" ] || [ -z "$branch" ]; then
      run git clone --depth 1 "$url" "$dir"
    else
      run git clone --depth 1 --branch "$branch" "$url" "$dir"
    fi
  fi
}

create_symlink() {
  local relpath="$1" link_name="$2" target_rel="$3"
  local target="$ROOT/$relpath/$target_rel"
  local link="$LINK_DIR/$link_name"

  is_safe_relpath "$target_rel" || die "unsafe symlink target: $target_rel"
  mkdir -p "$LINK_DIR"
  if [ ! -e "$target" ] && ! $DRY_RUN; then
    warn "symlink target missing: $target"
    return 0
  fi
  log "link links/$link_name -> $relpath/$target_rel"
  run ln -sfn "$target" "$link"
}

apply_patch_action() {
  local relpath="$1" patch_name="$2"
  case "$patch_name" in
    no-msolve)
      local f="$ROOT/$relpath/lbc_toolkit/common/systems_solvers.sage"
      if $DRY_RUN; then
        log "patch $relpath: remove explicit msolve algorithm"
        return 0
      fi
      if [ -f "$f" ]; then
        log "patch $relpath: remove explicit msolve algorithm"
        run sed -i "s/algorithm='msolve', //g" "$f"
      else
        warn "patch target not found: $f"
      fi
      ;;
    *) warn "unknown patch action: $patch_name" ;;
  esac
}

sage_install_editable() {
  local relpath="$1"
  local dir="$ROOT/$relpath"
  if ! $DO_SAGE_INSTALL; then
    log "skip Sage install for $relpath"
    return 0
  fi
  if ! command -v sage >/dev/null 2>&1; then
    warn "sage not found; cannot install $relpath into Sage"
    return 0
  fi
  log "sage editable install $relpath"
  run sage -python -m pip install -e "$dir"
}

PYTHONPATH_DIRS=()

handle_actions() {
  local relpath="$1" actions="$2"
  local action
  IFS=',' read -ra parts <<<"$actions"
  for action in "${parts[@]}"; do
    [ -n "$action" ] || continue
    case "$action" in
      pythonpath)
        PYTHONPATH_DIRS+=("$ROOT/$relpath")
        ;;
      sage-pip-editable)
        sage_install_editable "$relpath"
        ;;
      patch:*)
        apply_patch_action "$relpath" "${action#patch:}"
        ;;
      symlink:*)
        local spec="${action#symlink:}"
        local link_name="${spec%%:*}"
        local target_rel="${spec#*:}"
        [ "$link_name" != "$spec" ] || { warn "bad symlink action: $action"; continue; }
        create_symlink "$relpath" "$link_name" "$target_rel"
        ;;
      none)
        ;;
      *)
        warn "unknown action: $action"
        ;;
    esac
  done
}

generate_env() {
  local env_file="$ROOT/env.sh"
  local joined=""
  local dir

  PYTHONPATH_DIRS+=("$LINK_DIR")
  for dir in "${PYTHONPATH_DIRS[@]}"; do
    if [ -z "$joined" ]; then
      joined="$dir"
    else
      joined="$joined:$dir"
    fi
  done

  log "generate env.sh"
  if $DRY_RUN; then
    return 0
  fi
  cat > "$env_file" <<EOF
# Generated by crypto-libs/setup.sh. Source this file from your shell.
export CRYPTO_LIBS_ROOT="$ROOT"
export PYTHONPATH="$joined:\${PYTHONPATH:-}"

# kionactf/coppersmith backend locations. Override before sourcing if needed.
export COPPERSMITHFPLLLPATH="\${COPPERSMITHFPLLLPATH:-/usr/bin}"
export COPPERSMITHFLATTERPATH="\${COPPERSMITHFLATTERPATH:-/usr/local/bin}"
EOF
}

[ -f "$MANIFEST" ] || die "missing manifest: $MANIFEST"

while IFS=$'\034' read -r name relpath url branch actions desc; do
  [ -n "$name" ] || continue
  clone_or_update "$name" "$relpath" "$url" "$branch"
  handle_actions "$relpath" "$actions"
done < <(manifest_records)

generate_env

log "done"
log "next: source $ROOT/env.sh"
